name: Test create tag trigger

on:
  push:
    tags:
      - '*'
jobs:
  log-something:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "I'm running!!!!!!!github ref: ${{ github.ref }}, github.ref_name: ${{ github.ref_name }}"