name: Test paths-ignore
on:
  push:
    branches:
      - New-branch-4
    paths-ignore:
      - '**.md'
      - '.github/**'

jobs:
  log-something:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "I'm running!!!!!"